### ISSUE TITLE
I think your latest 1.6.2-beta needs an update.....

### ISSUE THREAD

**Issue by DumbJoe** [stsrki/KeepAliveHD#15]
Unless I'm wrong, 1 second interval isn't really 1 second, well it is for the first few seconds, but after that it takes long and longer.......eventually the 1 second interval will turn into a 30 second interval, 31 second interval, 50 second interval 2 minutes.....you get the idea..... I think this might be a thing for other intervals too, if you set it for 5 minutes, it's 5 minutes for the first few times but then gradually gets longer.....and longer......until that interval becomes too long that windows 10's USB standby/sleep mode kicks and rendering the drive dead and the only way to kick it going again is to pull out the plug and replug it in...and rinse and repeat with your KeepAliveHD program....

Now if you could somehow fix this bug such that it reads the the drive in its specified interval CONSISTENTLY, then your program will work for long hrs.....like more than 8 hrs straight of continuous work..... 

As it stands, it basically shits itself after the 1 hr mark forcing me to replug the damn USB drive.....2 hrs if your lucky.......

**Comment by DumbJoe** [comment]
.....and 12 minutes later and it just went to sleep..............

**Comment by stsrki** [comment]
That's really strange behaviour. Intervals should be equal every time. I will see what I can do.

**Comment by DumbJoe** [comment]
The write method at least appears to be consistent.....just need to fix up your read method......

**Comment by DumbJoe** [comment]
....so any updates or .....?

**Comment by stsrki** [comment]
Sorry but no. I'm very busy lately. If you could maybe try it yourself and create a PR I would gladly accept it.

**Comment by DumbJoe** [comment]
> Sorry but no. I'm very busy lately. If you could maybe try it yourself and create a PR I would gladly accept it.

Heh, I would if I knew how......unfortunately I'm not a programmer....so I leave all the programming stuff at the mercy of the original authors......and hope they don't abandon their projects.....hah...and if they do, well if I can find an alternative, then I guess it's alright but if there's no alternative, author is dead and I have no idea how to fix it up, then it would be gg for me! hahahaha

**Comment by stsrki** [comment]
I understand :)
Well the project is not abandoned, just that I don't have the time as I used to have. I will try to do something but it will take a while..

**Comment by DumbJoe** [comment]
ok, then I will wait and use the write method of the time being.........thanks! Will report any issues with the write or further issues with the read if I find out more so you can check it out! ☺

**Comment by supercoiled** [comment]
I have the same issue as DumbJoe.  I'm using Windows 10 Home on an 8GB laptop system with a 4TB Seagate Backup Plus attached to a USB 3.0 port.  Even with KeepaliveHD, the drive eventually goes to sleep.  I've tested different cables, ports, laptop and the result is unchanged - the drive goes to sleep at random times and I have to unplug and reattach to wake again.
BTW: Thank you for all your effort to date!

**Comment by DumbJoe** [comment]
ok, I think I know what happened here with my issue - looks like my external usb enclosure died or is dying(As I did have trouble earlier trying to connect it and draw/work on some school stuff but it wouldn't connect or open up), which was causing this finicky affect of once it being turned to standby mode, it's standby mode forever until you unplug and replug it back in. I chucked the internal drive into a new usb enclosure and bam, it wakes up fine after *sleeping*.

The enclosure was an ORICO 2588 series - model 2588us3-bl in case you're curious....I chucked it in it's big brother 3.5" enclosure and works fine even for a 2.5" drive.... lol the enclosure only lasted less than half a year....too bad I got the thing back in 2015 but never really used it since I didn't have a need for it until this year...so probably can't return for a replacement under warranty...hahaha

**Comment by stsrki** [comment]
@DumbJoe It's great you finally managed to find the culprit. So does this mean we can close the issue?

**Comment by DumbJoe** [comment]
Yes!
