### ISSUE TITLE
1.6.2 read does not work

### ISSUE THREAD

**Issue by GnomeBeans** [stsrki/KeepAliveHD#19]
I notice my drive going to sleep when read is set and I don't see any activity? I tried setting it to the root of the drive or a folder. Is there a trick to it? Thanks.

**Comment by stsrki** [comment]
I think you should define a folder where there is at least some files. So if you have any file in the root you should be fine. The way how it works in read-mode it randomly reads one byte from any file found in the specified directory.

**Comment by GnomeBeans** [comment]
Closing since I can confirm reads in task manager. Went from using a single folder with one text file to the drive letter which seems to work.
