### ISSUE TITLE
Any way to run this in non-interactive mode?

### ISSUE THREAD

**Issue by rpodric** [stsrki/KeepAliveHD#2]
Like in Task Scheduler, for example, so it's not dependent upon someone logging in.

I've tried doing that on Win10, and it certainly runs, but it doesn't do anything (Task Manager shows that reads/writes stop accruing immediately, and KeepAliveHD.txt is never updated). It's the same result when run as a service.

I've seen this with some programs before when trying to run this way, and sometimes it relates to the fact that their tray icon never appears, which is the case here. It doesn't really matter that it doesn't appear, since it's already configured--and the system may just be on with no user logged in anyway--except for the possibility that this may be what's stopping it from working when run like this.

Thanks for an ideas, and keep up the good work

**Comment by stsrki** [comment]
I think there is a lot of questions in case that I try to enable KeepAliveHD to be called from task Scheduler.

1. Under what account are you calling KAHD?
2. Is it the same as the account that you normally use to log in to windows?
3. What if the KAHD is already running and you try to open it, but now there is no tray icon available?

It's definitely not an easy thing to do, I will try to think of something.

**Comment by rpodric** [comment]
You may have already done it!  I was wrong. When answering your questions above and running KAHD normally again and looking at its Settings, I noticed that I had left it in a STOPPED state somehow when testing Task Scheduler yesterday. Oops.

So, it does work from Task Scheduler. Testing with 1.6.1. You don't get the tray icon, but that's completely normal (when running Dropbox this way, for example, you don't get its tray icon).

But this brings up something that I noticed, and this has nothing to do with Task Scheduler (here I'm talking only about running normally, for testing purposes): When in Read-only mode, KAHD doesn't read.  I verified this by watching Task Manager--the numbers (I/O read and/or I/O read bytes) don't move after the initial change upon starting the program. I see that you just added the Read-only feature, so this is just an early bug, I think. Unless I'm completely wrong again. :)

**Comment by stsrki** [comment]
If it's working then great. In that case maybe I can add feature that KAHD recognize that it's being run by the Task Scheduler and in that case it will automatically switch to STARTED mode.

About that read bug.. it will be fixed in the next version.

**Comment by rpodric** [comment]
Yes, if that's possible to do it might be a good idea, since as I found it's easy to make the mistake.

Thanks
